package com.sunfong.dtc.mapper.syncdata;

import com.sunfong.dtc.dob.entity.syncdata.DtcCurrentTask;

public interface DtcCurrentTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_CURRENT_TASK
     *
     * @mbg.generated 2018-12-06 16:07:07
     */
    int deleteByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_CURRENT_TASK
     *
     * @mbg.generated 2018-12-06 16:07:07
     */
    int insert(DtcCurrentTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_CURRENT_TASK
     *
     * @mbg.generated 2018-12-06 16:07:07
     */
    int insertSelective(DtcCurrentTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_CURRENT_TASK
     *
     * @mbg.generated 2018-12-06 16:07:07
     */
    DtcCurrentTask selectByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_CURRENT_TASK
     *
     * @mbg.generated 2018-12-06 16:07:07
     */
    int updateByPrimaryKeySelective(DtcCurrentTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_CURRENT_TASK
     *
     * @mbg.generated 2018-12-06 16:07:07
     */
    int updateByPrimaryKey(DtcCurrentTask record);
}