package com.sunfong.dtc.mapper.syncdata;

import com.sunfong.dtc.dob.entity.syncdata.DtcCurrentTaskDetail;

public interface DtcCurrentTaskDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_CURRENT_TASK_DETAIL
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    int deleteByPrimaryKey(String taskDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_CURRENT_TASK_DETAIL
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    int insert(DtcCurrentTaskDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_CURRENT_TASK_DETAIL
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    int insertSelective(DtcCurrentTaskDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_CURRENT_TASK_DETAIL
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    DtcCurrentTaskDetail selectByPrimaryKey(String taskDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_CURRENT_TASK_DETAIL
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    int updateByPrimaryKeySelective(DtcCurrentTaskDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_CURRENT_TASK_DETAIL
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    int updateByPrimaryKey(DtcCurrentTaskDetail record);
}