package com.sunfong.dtc.mapper.syncdata;

import com.sunfong.dtc.dob.entity.syncdata.DtcCompletedTask;

public interface DtcCompletedTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_COMPLETED_TASK
     *
     * @mbg.generated 2018-12-06 16:08:25
     */
    int deleteByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_COMPLETED_TASK
     *
     * @mbg.generated 2018-12-06 16:08:25
     */
    int insert(DtcCompletedTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_COMPLETED_TASK
     *
     * @mbg.generated 2018-12-06 16:08:25
     */
    int insertSelective(DtcCompletedTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_COMPLETED_TASK
     *
     * @mbg.generated 2018-12-06 16:08:25
     */
    DtcCompletedTask selectByPrimaryKey(String taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_COMPLETED_TASK
     *
     * @mbg.generated 2018-12-06 16:08:25
     */
    int updateByPrimaryKeySelective(DtcCompletedTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_COMPLETED_TASK
     *
     * @mbg.generated 2018-12-06 16:08:25
     */
    int updateByPrimaryKey(DtcCompletedTask record);
}