package com.sunfong.dtc.mapper.syncdata;

import com.sunfong.dtc.dob.entity.syncdata.DtcTableWhiteList;
import com.sunfong.dtc.dob.entity.syncdata.DtcTableWhiteListKey;

import java.util.List;

public interface DtcTableWhiteListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_TABLE_WHITE_LIST
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    int deleteByPrimaryKey(DtcTableWhiteListKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_TABLE_WHITE_LIST
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    int insert(DtcTableWhiteList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_TABLE_WHITE_LIST
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    int insertSelective(DtcTableWhiteList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_TABLE_WHITE_LIST
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    DtcTableWhiteList selectByPrimaryKey(DtcTableWhiteListKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_TABLE_WHITE_LIST
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    int updateByPrimaryKeySelective(DtcTableWhiteList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_TABLE_WHITE_LIST
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    int updateByPrimaryKey(DtcTableWhiteList record);

    List getTablesBySourceId(String id);
}