package com.sunfong.dtc.mapper.syncdata;

import com.sunfong.dtc.dob.entity.syncdata.DtcTableColsMapper;

public interface DtcTableColsMapperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_TABLE_COLS_MAPPER
     *
     * @mbg.generated 2018-12-06 16:06:28
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_TABLE_COLS_MAPPER
     *
     * @mbg.generated 2018-12-06 16:06:28
     */
    int insert(DtcTableColsMapper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_TABLE_COLS_MAPPER
     *
     * @mbg.generated 2018-12-06 16:06:28
     */
    int insertSelective(DtcTableColsMapper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_TABLE_COLS_MAPPER
     *
     * @mbg.generated 2018-12-06 16:06:28
     */
    DtcTableColsMapper selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_TABLE_COLS_MAPPER
     *
     * @mbg.generated 2018-12-06 16:06:28
     */
    int updateByPrimaryKeySelective(DtcTableColsMapper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_TABLE_COLS_MAPPER
     *
     * @mbg.generated 2018-12-06 16:06:28
     */
    int updateByPrimaryKey(DtcTableColsMapper record);
}