-- Create table
create table DTC_TABLE_COLS_MAPPER
(
  id                VARCHAR2(42) not null,
  src_id            VARCHAR2(42),
  src_col_name      VARCHAR2(30),
  src_col_data_type VARCHAR2(10),
  src_default_val   VARCHAR2(20),
  trg_id            VARCHAR2(42),
  trg_col_name      VARCHAR2(30),
  trg_col_data_type VARCHAR2(10),
  trg_default_val   VARCHAR2(20),
  src_table_name    VARCHAR2(50),
  trg_table_name    VARCHAR2(50),
  col_order         NUMBER
)
tablespace USERS
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
-- Add comments to the table
comment on table DTC_TABLE_COLS_MAPPER
  is '字段关系映射表';
-- Add comments to the columns
comment on column DTC_TABLE_COLS_MAPPER.id
  is '主键';
comment on column DTC_TABLE_COLS_MAPPER.src_id
  is '原始数据源Id';
comment on column DTC_TABLE_COLS_MAPPER.src_col_name
  is '原列名';
comment on column DTC_TABLE_COLS_MAPPER.src_col_data_type
  is '原列类型';
comment on column DTC_TABLE_COLS_MAPPER.src_default_val
  is '原缺省时写入值';
comment on column DTC_TABLE_COLS_MAPPER.trg_id
  is '目标数据源ID';
comment on column DTC_TABLE_COLS_MAPPER.trg_col_name
  is '目标列名';
comment on column DTC_TABLE_COLS_MAPPER.trg_col_data_type
  is '目标列类型';
comment on column DTC_TABLE_COLS_MAPPER.trg_default_val
  is '目标缺省时写入值';
comment on column DTC_TABLE_COLS_MAPPER.src_table_name
  is '原表名';
comment on column DTC_TABLE_COLS_MAPPER.trg_table_name
  is '目标表名';
comment on column DTC_TABLE_COLS_MAPPER.col_order
  is '排序';
-- Create/Recreate primary, unique and foreign key constraints
alter table DTC_TABLE_COLS_MAPPER
  add constraint DTC_TABLE_COLS_MAPPER_PK primary key (ID)
  using index
  tablespace USERS
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );


--测试数据
insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('100', '1', 'ACC_ITEM16', 'VARCHAR2', null, '1', 'ACC_ITEM16', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '33');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('101', '1', 'ITEM_CODE', 'VARCHAR2', null, '1', 'ITEM_CODE', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '34');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('102', '1', 'OUTLAY_CODE', 'VARCHAR2', null, '1', 'OUTLAY_CODE', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '35');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('103', '1', 'ITEM_ISN', 'INTEGER', null, '1', 'ITEM_ISN', 'INTEGER', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '36');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('104', '1', 'FIS_PERD', 'INTEGER', null, '1', 'FIS_PERD', 'INTEGER', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '37');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('105', '1', 'ACC_CODE', 'INTEGER', null, '1', 'ACC_CODE', 'INTEGER', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '38');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('106', '1', 'GUID', 'VARCHAR2', null, '1', 'GUID', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '39');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('107', '1', 'MODIFYTIME', 'INTEGER', null, '1', 'MODIFYTIME', 'INTEGER', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '40');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('108', '1', 'VOU_KIND', 'VARCHAR2', null, '1', 'VOU_KIND', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '41');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('109', '1', 'PRE_CHECK', 'NUMBER', null, '1', 'PRE_CHECK', 'NUMBER', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '42');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('110', '1', 'CHECK_NOTES', 'NUMBER', null, '1', 'CHECK_NOTES', 'NUMBER', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '43');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('111', '1', 'RELATION_FLAG', 'NUMBER', null, '1', 'RELATION_FLAG', 'NUMBER', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '44');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('112', '1', 'DETAIL_RELATION_FLAG', 'NUMBER', null, '1', 'DETAIL_RELATION_FLAG', 'NUMBER', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '45');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('113', '1', 'SUMGUID', 'NUMBER', null, '1', 'SUMGUID', 'NUMBER', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '46');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('68', '1', 'VOU_NO', 'VARCHAR2', null, '1', 'VOU_NO', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '1');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('69', '1', 'CO_CODE', 'VARCHAR2', null, '1', 'CO_CODE', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '2');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('70', '1', 'ACCOUNT_ID', 'VARCHAR2', '120', '1', 'ACCOUNT_ID', 'VARCHAR2', '10610', 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '3');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('71', '1', 'FISCAL', 'VARCHAR2', null, '1', 'FISCAL', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '4');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('72', '1', 'VOU_SEQ', 'VARCHAR2', null, '1', 'VOU_SEQ', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '5');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('73', '1', 'VOU_DETAIL_SEQ', 'VARCHAR2', null, '1', 'VOU_DETAIL_SEQ', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '6');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('74', '1', 'B_ACC_CODE', 'VARCHAR2', null, '1', 'B_ACC_CODE', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '7');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('75', '1', 'DR_CR', 'VARCHAR2', null, '1', 'DR_CR', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '8');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('76', '1', 'CUR_CODE', 'VARCHAR2', null, '1', 'CUR_CODE', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '9');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('77', '1', 'EX_RATE', 'DATE', null, '1', 'EX_RATE', 'DATE', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '10');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('78', '1', 'CURR_AMT', 'VARCHAR2', null, '1', 'CURR_AMT', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '11');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('79', '1', 'STAD_AMT', 'VARCHAR2', null, '1', 'STAD_AMT', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '12');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('80', '1', 'QTY', 'VARCHAR2', null, '1', 'QTY', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '13');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('81', '1', 'PRICE', 'VARCHAR2', null, '1', 'PRICE', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '14');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('82', '1', 'ACC_ITEM1', 'VARCHAR2', null, '1', 'ACC_ITEM1', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '15');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('83', '1', 'ACC_ITEM2', 'VARCHAR2', null, '1', 'ACC_ITEM2', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '16');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('84', '1', 'ACC_ITEM3', 'VARCHAR2', null, '1', 'ACC_ITEM3', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '17');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('85', '1', 'ACC_ITEM4', 'VARCHAR2', null, '1', 'ACC_ITEM4', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '18');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('86', '1', 'ACC_ITEM5', 'VARCHAR2', null, '1', 'ACC_ITEM5', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '19');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('87', '1', 'ACC_ITEM6', 'VARCHAR2', null, '1', 'ACC_ITEM6', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '20');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('88', '1', 'ACC_ITEM7', 'VARCHAR2', null, '1', 'ACC_ITEM7', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '21');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('89', '1', 'ACC_ITEM8', 'VARCHAR2', null, '1', 'ACC_ITEM8', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '22');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('90', '1', 'B_CO_CODE', 'INTEGER', null, '1', 'B_CO_CODE', 'INTEGER', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '23');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('91', '1', 'BUSS_DATE', 'VARCHAR2', null, '1', 'BUSS_DATE', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '24');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('92', '1', 'BOD_NO', 'NUMBER', null, '1', 'BOD_NO', 'NUMBER', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '25');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('93', '1', 'ACC_ITEM10', 'DATE', null, '1', 'ACC_ITEM10', 'DATE', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '26');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('94', '1', 'ACC_ITEM9', 'VARCHAR2', null, '1', 'ACC_ITEM9', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '27');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('95', '1', 'ACC_ITEM11', 'CHAR', null, '1', 'ACC_ITEM11', 'CHAR', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '28');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('96', '1', 'ACC_ITEM12', 'VARCHAR2', null, '1', 'ACC_ITEM12', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '29');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('97', '1', 'ACC_ITEM13', 'VARCHAR2', null, '1', 'ACC_ITEM13', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '30');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('98', '1', 'ACC_ITEM14', 'VARCHAR2', null, '1', 'ACC_ITEM14', 'VARCHAR2', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '31');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('99', '1', 'ACC_ITEM15', 'NUMBER', null, '1', 'ACC_ITEM15', 'NUMBER', null, 'GL_VOU_DETAIL_ASS', 'GL_VOU_DETAIL_ASS', '32');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('1', '1', 'VOU_NO', 'VARCHAR2', 'GN-09-0007', '1', 'VOU_NO', 'VARCHAR2', 'a123', 'VW_GL_VOU_HEAD', 'GL_VOU_HEAD_TEST', '1');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('2', '1', 'CO_CODE', 'VARCHAR2', '441299', '1', 'CO_CODE', 'VARCHAR2', '123', 'VW_GL_VOU_HEAD', 'GL_VOU_HEAD_TEST', '2');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('3', '1', 'ACCOUNT_ID', 'VARCHAR2', null, '1', 'VOU_DESC', 'VARCHAR2', null, 'VW_GL_VOU_HEAD', 'GL_VOU_HEAD_TEST', '3');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('4', '1', 'FISCAL', 'INTEGER', null, '1', 'FISCAL', 'INTEGER', null, 'VW_GL_VOU_HEAD', 'GL_VOU_HEAD_TEST', '4');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('5', '1', 'FIS_PERD', 'INTEGER', null, '1', 'FIS_PERD', 'INTEGER', null, 'VW_GL_VOU_HEAD', 'GL_VOU_HEAD_TEST', '5');

insert into DTC_TABLE_COLS_MAPPER (ID, SRC_ID, SRC_COL_NAME, SRC_COL_DATA_TYPE, SRC_DEFAULT_VAL, TRG_ID, TRG_COL_NAME, TRG_COL_DATA_TYPE, TRG_DEFAULT_VAL, SRC_TABLE_NAME, TRG_TABLE_NAME, COL_ORDER)
values ('6', '1', 'VOU_TYPE_CODE', 'VARCHAR2', null, '1', 'VOU_TYPE_CODE', 'VARCHAR2', null, 'VW_GL_VOU_HEAD', 'GL_VOU_HEAD_TEST', '6');