package com.sunfong.dtc.dob.entity.webservice;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table DTC_WS_CONFIG
 *
 * @mbg.generated do_not_delete_during_merge 2018-12-19 15:28:39
 */
public class DtcWsConfig implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_WS_CONFIG.ID
     *
     * @mbg.generated 2018-12-19 15:28:39
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_WS_CONFIG.URL
     *
     * @mbg.generated 2018-12-19 15:28:39
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_WS_CONFIG.NAME_SPACE
     *
     * @mbg.generated 2018-12-19 15:28:39
     */
    private String nameSpace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_WS_CONFIG.OPT_ACHV_TYPE
     *
     * @mbg.generated 2018-12-19 15:28:39
     */
    private String optAchvType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DTC_WS_CONFIG
     *
     * @mbg.generated 2018-12-19 15:28:39
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_WS_CONFIG.ID
     *
     * @return the value of DTC_WS_CONFIG.ID
     *
     * @mbg.generated 2018-12-19 15:28:39
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_WS_CONFIG.ID
     *
     * @param id the value for DTC_WS_CONFIG.ID
     *
     * @mbg.generated 2018-12-19 15:28:39
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_WS_CONFIG.URL
     *
     * @return the value of DTC_WS_CONFIG.URL
     *
     * @mbg.generated 2018-12-19 15:28:39
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_WS_CONFIG.URL
     *
     * @param url the value for DTC_WS_CONFIG.URL
     *
     * @mbg.generated 2018-12-19 15:28:39
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_WS_CONFIG.NAME_SPACE
     *
     * @return the value of DTC_WS_CONFIG.NAME_SPACE
     *
     * @mbg.generated 2018-12-19 15:28:39
     */
    public String getNameSpace() {
        return nameSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_WS_CONFIG.NAME_SPACE
     *
     * @param nameSpace the value for DTC_WS_CONFIG.NAME_SPACE
     *
     * @mbg.generated 2018-12-19 15:28:39
     */
    public void setNameSpace(String nameSpace) {
        this.nameSpace = nameSpace == null ? null : nameSpace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_WS_CONFIG.OPT_ACHV_TYPE
     *
     * @return the value of DTC_WS_CONFIG.OPT_ACHV_TYPE
     *
     * @mbg.generated 2018-12-19 15:28:39
     */
    public String getOptAchvType() {
        return optAchvType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_WS_CONFIG.OPT_ACHV_TYPE
     *
     * @param optAchvType the value for DTC_WS_CONFIG.OPT_ACHV_TYPE
     *
     * @mbg.generated 2018-12-19 15:28:39
     */
    public void setOptAchvType(String optAchvType) {
        this.optAchvType = optAchvType == null ? null : optAchvType.trim();
    }
}