package com.sunfong.dtc.dob.entity.syncdata;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table DTC_COMPLETED_TASK
 *
 * @mbg.generated do_not_delete_during_merge 2018-12-06 16:08:25
 */
public class DtcCompletedTask implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_COMPLETED_TASK.TASK_ID
     *
     * @mbg.generated 2018-12-06 16:08:25
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_COMPLETED_TASK.TABLE_NAME
     *
     * @mbg.generated 2018-12-06 16:08:25
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_COMPLETED_TASK.SYNC_NUMS_PER_PAGE
     *
     * @mbg.generated 2018-12-06 16:08:25
     */
    private Integer syncNumsPerPage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_COMPLETED_TASK.TOTAL_NUMS
     *
     * @mbg.generated 2018-12-06 16:08:25
     */
    private Integer totalNums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_COMPLETED_TASK.CURRENT_PAGE_NO
     *
     * @mbg.generated 2018-12-06 16:08:25
     */
    private Integer currentPageNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_COMPLETED_TASK.TOTAL_PAGES
     *
     * @mbg.generated 2018-12-06 16:08:25
     */
    private Integer totalPages;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_COMPLETED_TASK.BATCH_NO
     *
     * @mbg.generated 2018-12-06 16:08:25
     */
    private String batchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DTC_COMPLETED_TASK
     *
     * @mbg.generated 2018-12-06 16:08:25
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_COMPLETED_TASK.TASK_ID
     *
     * @return the value of DTC_COMPLETED_TASK.TASK_ID
     *
     * @mbg.generated 2018-12-06 16:08:25
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_COMPLETED_TASK.TASK_ID
     *
     * @param taskId the value for DTC_COMPLETED_TASK.TASK_ID
     *
     * @mbg.generated 2018-12-06 16:08:25
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_COMPLETED_TASK.TABLE_NAME
     *
     * @return the value of DTC_COMPLETED_TASK.TABLE_NAME
     *
     * @mbg.generated 2018-12-06 16:08:25
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_COMPLETED_TASK.TABLE_NAME
     *
     * @param tableName the value for DTC_COMPLETED_TASK.TABLE_NAME
     *
     * @mbg.generated 2018-12-06 16:08:25
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_COMPLETED_TASK.SYNC_NUMS_PER_PAGE
     *
     * @return the value of DTC_COMPLETED_TASK.SYNC_NUMS_PER_PAGE
     *
     * @mbg.generated 2018-12-06 16:08:25
     */
    public Integer getSyncNumsPerPage() {
        return syncNumsPerPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_COMPLETED_TASK.SYNC_NUMS_PER_PAGE
     *
     * @param syncNumsPerPage the value for DTC_COMPLETED_TASK.SYNC_NUMS_PER_PAGE
     *
     * @mbg.generated 2018-12-06 16:08:25
     */
    public void setSyncNumsPerPage(Integer syncNumsPerPage) {
        this.syncNumsPerPage = syncNumsPerPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_COMPLETED_TASK.TOTAL_NUMS
     *
     * @return the value of DTC_COMPLETED_TASK.TOTAL_NUMS
     *
     * @mbg.generated 2018-12-06 16:08:25
     */
    public Integer getTotalNums() {
        return totalNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_COMPLETED_TASK.TOTAL_NUMS
     *
     * @param totalNums the value for DTC_COMPLETED_TASK.TOTAL_NUMS
     *
     * @mbg.generated 2018-12-06 16:08:25
     */
    public void setTotalNums(Integer totalNums) {
        this.totalNums = totalNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_COMPLETED_TASK.CURRENT_PAGE_NO
     *
     * @return the value of DTC_COMPLETED_TASK.CURRENT_PAGE_NO
     *
     * @mbg.generated 2018-12-06 16:08:25
     */
    public Integer getCurrentPageNo() {
        return currentPageNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_COMPLETED_TASK.CURRENT_PAGE_NO
     *
     * @param currentPageNo the value for DTC_COMPLETED_TASK.CURRENT_PAGE_NO
     *
     * @mbg.generated 2018-12-06 16:08:25
     */
    public void setCurrentPageNo(Integer currentPageNo) {
        this.currentPageNo = currentPageNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_COMPLETED_TASK.TOTAL_PAGES
     *
     * @return the value of DTC_COMPLETED_TASK.TOTAL_PAGES
     *
     * @mbg.generated 2018-12-06 16:08:25
     */
    public Integer getTotalPages() {
        return totalPages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_COMPLETED_TASK.TOTAL_PAGES
     *
     * @param totalPages the value for DTC_COMPLETED_TASK.TOTAL_PAGES
     *
     * @mbg.generated 2018-12-06 16:08:25
     */
    public void setTotalPages(Integer totalPages) {
        this.totalPages = totalPages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_COMPLETED_TASK.BATCH_NO
     *
     * @return the value of DTC_COMPLETED_TASK.BATCH_NO
     *
     * @mbg.generated 2018-12-06 16:08:25
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_COMPLETED_TASK.BATCH_NO
     *
     * @param batchNo the value for DTC_COMPLETED_TASK.BATCH_NO
     *
     * @mbg.generated 2018-12-06 16:08:25
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo == null ? null : batchNo.trim();
    }
}