package com.sunfong.dtc.dob.entity.syncdata;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table DTC_CURRENT_TASK_DETAIL
 *
 * @mbg.generated do_not_delete_during_merge 2018-12-06 16:07:35
 */
public class DtcCurrentTaskDetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_CURRENT_TASK_DETAIL.TASK_DETAIL_ID
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    private String taskDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_CURRENT_TASK_DETAIL.TABLE_NAME
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_CURRENT_TASK_DETAIL.SYNC_NUMS_PER_PAGE
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    private Integer syncNumsPerPage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_CURRENT_TASK_DETAIL.TOTAL_NUMS
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    private Integer totalNums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_CURRENT_TASK_DETAIL.CURRENT_PAGE_NO
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    private Integer currentPageNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_CURRENT_TASK_DETAIL.TOTAL_PAGES
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    private Integer totalPages;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_CURRENT_TASK_DETAIL.MAIN_TASK_ID
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    private String mainTaskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_CURRENT_TASK_DETAIL.OPT_TYPE
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    private String optType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_CURRENT_TASK_DETAIL.TASK_DESC
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    private String taskDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_CURRENT_TASK_DETAIL.OPT_PARAMS
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    private String optParams;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_CURRENT_TASK_DETAIL.OPT_SEQ
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    private Integer optSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_CURRENT_TASK_DETAIL.IS_REF_BEFORRE
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    private String isRefBeforre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_CURRENT_TASK_DETAIL.SOURCE_ID
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    private String sourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_CURRENT_TASK_DETAIL.CREATE_DATE
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_CURRENT_TASK_DETAIL.TRG_TABLE_NAME
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    private String trgTableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DTC_CURRENT_TASK_DETAIL
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_CURRENT_TASK_DETAIL.TASK_DETAIL_ID
     *
     * @return the value of DTC_CURRENT_TASK_DETAIL.TASK_DETAIL_ID
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public String getTaskDetailId() {
        return taskDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_CURRENT_TASK_DETAIL.TASK_DETAIL_ID
     *
     * @param taskDetailId the value for DTC_CURRENT_TASK_DETAIL.TASK_DETAIL_ID
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public void setTaskDetailId(String taskDetailId) {
        this.taskDetailId = taskDetailId == null ? null : taskDetailId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_CURRENT_TASK_DETAIL.TABLE_NAME
     *
     * @return the value of DTC_CURRENT_TASK_DETAIL.TABLE_NAME
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_CURRENT_TASK_DETAIL.TABLE_NAME
     *
     * @param tableName the value for DTC_CURRENT_TASK_DETAIL.TABLE_NAME
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_CURRENT_TASK_DETAIL.SYNC_NUMS_PER_PAGE
     *
     * @return the value of DTC_CURRENT_TASK_DETAIL.SYNC_NUMS_PER_PAGE
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public Integer getSyncNumsPerPage() {
        return syncNumsPerPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_CURRENT_TASK_DETAIL.SYNC_NUMS_PER_PAGE
     *
     * @param syncNumsPerPage the value for DTC_CURRENT_TASK_DETAIL.SYNC_NUMS_PER_PAGE
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public void setSyncNumsPerPage(Integer syncNumsPerPage) {
        this.syncNumsPerPage = syncNumsPerPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_CURRENT_TASK_DETAIL.TOTAL_NUMS
     *
     * @return the value of DTC_CURRENT_TASK_DETAIL.TOTAL_NUMS
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public Integer getTotalNums() {
        return totalNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_CURRENT_TASK_DETAIL.TOTAL_NUMS
     *
     * @param totalNums the value for DTC_CURRENT_TASK_DETAIL.TOTAL_NUMS
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public void setTotalNums(Integer totalNums) {
        this.totalNums = totalNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_CURRENT_TASK_DETAIL.CURRENT_PAGE_NO
     *
     * @return the value of DTC_CURRENT_TASK_DETAIL.CURRENT_PAGE_NO
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public Integer getCurrentPageNo() {
        return currentPageNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_CURRENT_TASK_DETAIL.CURRENT_PAGE_NO
     *
     * @param currentPageNo the value for DTC_CURRENT_TASK_DETAIL.CURRENT_PAGE_NO
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public void setCurrentPageNo(Integer currentPageNo) {
        this.currentPageNo = currentPageNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_CURRENT_TASK_DETAIL.TOTAL_PAGES
     *
     * @return the value of DTC_CURRENT_TASK_DETAIL.TOTAL_PAGES
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public Integer getTotalPages() {
        return totalPages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_CURRENT_TASK_DETAIL.TOTAL_PAGES
     *
     * @param totalPages the value for DTC_CURRENT_TASK_DETAIL.TOTAL_PAGES
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public void setTotalPages(Integer totalPages) {
        this.totalPages = totalPages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_CURRENT_TASK_DETAIL.MAIN_TASK_ID
     *
     * @return the value of DTC_CURRENT_TASK_DETAIL.MAIN_TASK_ID
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public String getMainTaskId() {
        return mainTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_CURRENT_TASK_DETAIL.MAIN_TASK_ID
     *
     * @param mainTaskId the value for DTC_CURRENT_TASK_DETAIL.MAIN_TASK_ID
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public void setMainTaskId(String mainTaskId) {
        this.mainTaskId = mainTaskId == null ? null : mainTaskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_CURRENT_TASK_DETAIL.OPT_TYPE
     *
     * @return the value of DTC_CURRENT_TASK_DETAIL.OPT_TYPE
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public String getOptType() {
        return optType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_CURRENT_TASK_DETAIL.OPT_TYPE
     *
     * @param optType the value for DTC_CURRENT_TASK_DETAIL.OPT_TYPE
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public void setOptType(String optType) {
        this.optType = optType == null ? null : optType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_CURRENT_TASK_DETAIL.TASK_DESC
     *
     * @return the value of DTC_CURRENT_TASK_DETAIL.TASK_DESC
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public String getTaskDesc() {
        return taskDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_CURRENT_TASK_DETAIL.TASK_DESC
     *
     * @param taskDesc the value for DTC_CURRENT_TASK_DETAIL.TASK_DESC
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public void setTaskDesc(String taskDesc) {
        this.taskDesc = taskDesc == null ? null : taskDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_CURRENT_TASK_DETAIL.OPT_PARAMS
     *
     * @return the value of DTC_CURRENT_TASK_DETAIL.OPT_PARAMS
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public String getOptParams() {
        return optParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_CURRENT_TASK_DETAIL.OPT_PARAMS
     *
     * @param optParams the value for DTC_CURRENT_TASK_DETAIL.OPT_PARAMS
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public void setOptParams(String optParams) {
        this.optParams = optParams == null ? null : optParams.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_CURRENT_TASK_DETAIL.OPT_SEQ
     *
     * @return the value of DTC_CURRENT_TASK_DETAIL.OPT_SEQ
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public Integer getOptSeq() {
        return optSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_CURRENT_TASK_DETAIL.OPT_SEQ
     *
     * @param optSeq the value for DTC_CURRENT_TASK_DETAIL.OPT_SEQ
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public void setOptSeq(Integer optSeq) {
        this.optSeq = optSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_CURRENT_TASK_DETAIL.IS_REF_BEFORRE
     *
     * @return the value of DTC_CURRENT_TASK_DETAIL.IS_REF_BEFORRE
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public String getIsRefBeforre() {
        return isRefBeforre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_CURRENT_TASK_DETAIL.IS_REF_BEFORRE
     *
     * @param isRefBeforre the value for DTC_CURRENT_TASK_DETAIL.IS_REF_BEFORRE
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public void setIsRefBeforre(String isRefBeforre) {
        this.isRefBeforre = isRefBeforre == null ? null : isRefBeforre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_CURRENT_TASK_DETAIL.SOURCE_ID
     *
     * @return the value of DTC_CURRENT_TASK_DETAIL.SOURCE_ID
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public String getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_CURRENT_TASK_DETAIL.SOURCE_ID
     *
     * @param sourceId the value for DTC_CURRENT_TASK_DETAIL.SOURCE_ID
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public void setSourceId(String sourceId) {
        this.sourceId = sourceId == null ? null : sourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_CURRENT_TASK_DETAIL.CREATE_DATE
     *
     * @return the value of DTC_CURRENT_TASK_DETAIL.CREATE_DATE
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_CURRENT_TASK_DETAIL.CREATE_DATE
     *
     * @param createDate the value for DTC_CURRENT_TASK_DETAIL.CREATE_DATE
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_CURRENT_TASK_DETAIL.TRG_TABLE_NAME
     *
     * @return the value of DTC_CURRENT_TASK_DETAIL.TRG_TABLE_NAME
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public String getTrgTableName() {
        return trgTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_CURRENT_TASK_DETAIL.TRG_TABLE_NAME
     *
     * @param trgTableName the value for DTC_CURRENT_TASK_DETAIL.TRG_TABLE_NAME
     *
     * @mbg.generated 2018-12-06 16:07:35
     */
    public void setTrgTableName(String trgTableName) {
        this.trgTableName = trgTableName == null ? null : trgTableName.trim();
    }
}