package com.sunfong.dtc.dob.entity.syncdata;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table DTC_CURRENT_TASK
 *
 * @mbg.generated do_not_delete_during_merge 2018-12-06 16:07:07
 */
public class DtcCurrentTask implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_CURRENT_TASK.TASK_ID
     *
     * @mbg.generated 2018-12-06 16:07:07
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_CURRENT_TASK.TASK_NAME
     *
     * @mbg.generated 2018-12-06 16:07:07
     */
    private String taskName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_CURRENT_TASK.TASK_DESC
     *
     * @mbg.generated 2018-12-06 16:07:07
     */
    private String taskDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_CURRENT_TASK.CREATE_DATE
     *
     * @mbg.generated 2018-12-06 16:07:07
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_CURRENT_TASK.EXECUTOR
     *
     * @mbg.generated 2018-12-06 16:07:07
     */
    private String executor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_CURRENT_TASK.PERCENT
     *
     * @mbg.generated 2018-12-06 16:07:07
     */
    private Integer percent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DTC_CURRENT_TASK
     *
     * @mbg.generated 2018-12-06 16:07:07
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_CURRENT_TASK.TASK_ID
     *
     * @return the value of DTC_CURRENT_TASK.TASK_ID
     *
     * @mbg.generated 2018-12-06 16:07:07
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_CURRENT_TASK.TASK_ID
     *
     * @param taskId the value for DTC_CURRENT_TASK.TASK_ID
     *
     * @mbg.generated 2018-12-06 16:07:07
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_CURRENT_TASK.TASK_NAME
     *
     * @return the value of DTC_CURRENT_TASK.TASK_NAME
     *
     * @mbg.generated 2018-12-06 16:07:07
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_CURRENT_TASK.TASK_NAME
     *
     * @param taskName the value for DTC_CURRENT_TASK.TASK_NAME
     *
     * @mbg.generated 2018-12-06 16:07:07
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_CURRENT_TASK.TASK_DESC
     *
     * @return the value of DTC_CURRENT_TASK.TASK_DESC
     *
     * @mbg.generated 2018-12-06 16:07:07
     */
    public String getTaskDesc() {
        return taskDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_CURRENT_TASK.TASK_DESC
     *
     * @param taskDesc the value for DTC_CURRENT_TASK.TASK_DESC
     *
     * @mbg.generated 2018-12-06 16:07:07
     */
    public void setTaskDesc(String taskDesc) {
        this.taskDesc = taskDesc == null ? null : taskDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_CURRENT_TASK.CREATE_DATE
     *
     * @return the value of DTC_CURRENT_TASK.CREATE_DATE
     *
     * @mbg.generated 2018-12-06 16:07:07
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_CURRENT_TASK.CREATE_DATE
     *
     * @param createDate the value for DTC_CURRENT_TASK.CREATE_DATE
     *
     * @mbg.generated 2018-12-06 16:07:07
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_CURRENT_TASK.EXECUTOR
     *
     * @return the value of DTC_CURRENT_TASK.EXECUTOR
     *
     * @mbg.generated 2018-12-06 16:07:07
     */
    public String getExecutor() {
        return executor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_CURRENT_TASK.EXECUTOR
     *
     * @param executor the value for DTC_CURRENT_TASK.EXECUTOR
     *
     * @mbg.generated 2018-12-06 16:07:07
     */
    public void setExecutor(String executor) {
        this.executor = executor == null ? null : executor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_CURRENT_TASK.PERCENT
     *
     * @return the value of DTC_CURRENT_TASK.PERCENT
     *
     * @mbg.generated 2018-12-06 16:07:07
     */
    public Integer getPercent() {
        return percent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_CURRENT_TASK.PERCENT
     *
     * @param percent the value for DTC_CURRENT_TASK.PERCENT
     *
     * @mbg.generated 2018-12-06 16:07:07
     */
    public void setPercent(Integer percent) {
        this.percent = percent;
    }
}