package com.sunfong.dtc.dob.entity.syncdata;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table DTC_TABLE_WHITE_LIST
 *
 * @mbg.generated do_not_delete_during_merge 2018-12-06 16:05:48
 */
public class DtcTableWhiteListKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_TABLE_WHITE_LIST.SOURCE_ID
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    private String sourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_TABLE_WHITE_LIST.TABLE_NAME
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DTC_TABLE_WHITE_LIST
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_TABLE_WHITE_LIST.SOURCE_ID
     *
     * @return the value of DTC_TABLE_WHITE_LIST.SOURCE_ID
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    public String getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_TABLE_WHITE_LIST.SOURCE_ID
     *
     * @param sourceId the value for DTC_TABLE_WHITE_LIST.SOURCE_ID
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    public void setSourceId(String sourceId) {
        this.sourceId = sourceId == null ? null : sourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_TABLE_WHITE_LIST.TABLE_NAME
     *
     * @return the value of DTC_TABLE_WHITE_LIST.TABLE_NAME
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_TABLE_WHITE_LIST.TABLE_NAME
     *
     * @param tableName the value for DTC_TABLE_WHITE_LIST.TABLE_NAME
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }
}