package com.sunfong.dtc.dob.entity.syncdata;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table DTC_TABLE_WHITE_LIST
 *
 * @mbg.generated do_not_delete_during_merge 2018-12-06 16:05:48
 */
public class DtcTableWhiteList extends DtcTableWhiteListKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_TABLE_WHITE_LIST.SOURCE_NAME
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    private String sourceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_TABLE_WHITE_LIST.SYNC_NUMS_PER_PAGE
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    private Integer syncNumsPerPage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_TABLE_WHITE_LIST.IS_USE_PARAMS
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    private String isUseParams;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_TABLE_WHITE_LIST.PARAMS
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    private String params;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_TABLE_WHITE_LIST.SYNC_SEQ
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    private Integer syncSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTC_TABLE_WHITE_LIST.TRG_TABLE_NAME
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    private String trgTableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DTC_TABLE_WHITE_LIST
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_TABLE_WHITE_LIST.SOURCE_NAME
     *
     * @return the value of DTC_TABLE_WHITE_LIST.SOURCE_NAME
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    public String getSourceName() {
        return sourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_TABLE_WHITE_LIST.SOURCE_NAME
     *
     * @param sourceName the value for DTC_TABLE_WHITE_LIST.SOURCE_NAME
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    public void setSourceName(String sourceName) {
        this.sourceName = sourceName == null ? null : sourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_TABLE_WHITE_LIST.SYNC_NUMS_PER_PAGE
     *
     * @return the value of DTC_TABLE_WHITE_LIST.SYNC_NUMS_PER_PAGE
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    public Integer getSyncNumsPerPage() {
        return syncNumsPerPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_TABLE_WHITE_LIST.SYNC_NUMS_PER_PAGE
     *
     * @param syncNumsPerPage the value for DTC_TABLE_WHITE_LIST.SYNC_NUMS_PER_PAGE
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    public void setSyncNumsPerPage(Integer syncNumsPerPage) {
        this.syncNumsPerPage = syncNumsPerPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_TABLE_WHITE_LIST.IS_USE_PARAMS
     *
     * @return the value of DTC_TABLE_WHITE_LIST.IS_USE_PARAMS
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    public String getIsUseParams() {
        return isUseParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_TABLE_WHITE_LIST.IS_USE_PARAMS
     *
     * @param isUseParams the value for DTC_TABLE_WHITE_LIST.IS_USE_PARAMS
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    public void setIsUseParams(String isUseParams) {
        this.isUseParams = isUseParams == null ? null : isUseParams.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_TABLE_WHITE_LIST.PARAMS
     *
     * @return the value of DTC_TABLE_WHITE_LIST.PARAMS
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_TABLE_WHITE_LIST.PARAMS
     *
     * @param params the value for DTC_TABLE_WHITE_LIST.PARAMS
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_TABLE_WHITE_LIST.SYNC_SEQ
     *
     * @return the value of DTC_TABLE_WHITE_LIST.SYNC_SEQ
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    public Integer getSyncSeq() {
        return syncSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_TABLE_WHITE_LIST.SYNC_SEQ
     *
     * @param syncSeq the value for DTC_TABLE_WHITE_LIST.SYNC_SEQ
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    public void setSyncSeq(Integer syncSeq) {
        this.syncSeq = syncSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTC_TABLE_WHITE_LIST.TRG_TABLE_NAME
     *
     * @return the value of DTC_TABLE_WHITE_LIST.TRG_TABLE_NAME
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    public String getTrgTableName() {
        return trgTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTC_TABLE_WHITE_LIST.TRG_TABLE_NAME
     *
     * @param trgTableName the value for DTC_TABLE_WHITE_LIST.TRG_TABLE_NAME
     *
     * @mbg.generated 2018-12-06 16:05:48
     */
    public void setTrgTableName(String trgTableName) {
        this.trgTableName = trgTableName == null ? null : trgTableName.trim();
    }
}