spring:
  #oracle
  application:
    name: dtc
  datasource:
    url: jdbc:oracle:thin:@192.168.29.134:1521:orcl
    username: dtc
    password: 1
    driver-class-name: oracle.jdbc.driver.OracleDriver
  thymeleaf:
    cache: false
  #注册中心
eureka:
  client:
    service-url:
      defaultZoon: http://localhost:8761/eureka
#  application:
#    name: dtc
#  cloud:
#    consul:
#      host: 127.0.0.1
#      port: 8500
#      discovery:
#        register: true
#        hostname: 127.0.0.1
#        serviceName: ${spring.application.name}
#        port: ${server.port}
#        healthCheckPath: /data/dtc/check/alive
#        healthCheckInterval: 15s
#        tags: urlprefix-/${spring.application.name}
#        instanceId: ${spring.application.name}






mybatis:
  mapper-locations: classpath:static/dtc/mapper/*/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8020

logging:
  level:
     com.sunfong.dtc : debug





