package com.sunfong.dtc.mapper.webservice;

import com.sunfong.dtc.dob.entity.webservice.DtcWsConfig;
import org.springframework.stereotype.Component;

@Component(value = "dtcWsConfigMapper")
public interface DtcWsConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_WS_CONFIG
     *
     * @mbg.generated 2018-12-19 15:28:39
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_WS_CONFIG
     *
     * @mbg.generated 2018-12-19 15:28:39
     */
    int insert(DtcWsConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_WS_CONFIG
     *
     * @mbg.generated 2018-12-19 15:28:39
     */
    int insertSelective(DtcWsConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_WS_CONFIG
     *
     * @mbg.generated 2018-12-19 15:28:39
     */
    DtcWsConfig selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_WS_CONFIG
     *
     * @mbg.generated 2018-12-19 15:28:39
     */
    int updateByPrimaryKeySelective(DtcWsConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTC_WS_CONFIG
     *
     * @mbg.generated 2018-12-19 15:28:39
     */
    int updateByPrimaryKey(DtcWsConfig record);

    DtcWsConfig selectById(String id);
}